# Generated by Django 2.1.7 on 2019-03-05 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='subscribe',
            field=models.ManyToManyField(related_name='subscribed_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
