# Generated by Django 2.1.7 on 2019-03-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='subscribe',
            new_name='subscribers',
        ),
    ]
