# Generated by Django 2.1.7 on 2019-03-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_embed_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='embed',
        ),
    ]
