# Generated by Django 2.1.7 on 2019-03-07 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_remove_subject_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boards.Board'),
            preserve_default=False,
        ),
    ]
