# Generated by Django 2.1.7 on 2019-03-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_embed_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embed',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board', verbose_name='Kategoria'),
        ),
    ]
