# Generated by Django 2.1.7 on 2019-03-07 13:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20190307_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='embed',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedboards', to='boards.Board', verbose_name='Kategoria'),
        ),
    ]
