# Generated by Django 2.1.7 on 2019-03-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_subscribe_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embed',
            name='board',
        ),
    ]
