# Generated by Django 2.1.7 on 2019-03-09 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_remove_embed_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dział'},
        ),
        migrations.AlterModelOptions(
            name='embed',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post'},
        ),
        migrations.AddField(
            model_name='embed',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Board'),
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board-cover', verbose_name='Tło kategorii'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='boards.Board', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='body',
            field=models.TextField(blank=True, verbose_name='Treść'),
        ),
    ]
